library(readr)
library(ggplot2)
#library(caret)
synthetic_control <- read_table("~/Downloads/Work/Thesis/synthetic_control.data", col_names = FALSE)
#library(factoextra)
#library(aricode)
#library(clevr)
library(cluster)
library(stringr)
#library(ClusterR)
library(dtwclust)
library(data.table)
library(hash)
library(tidytable)
