setwd("/home/scyther/Documents/clustergi/K Means/")
alg<-c("Hartigan-Wong", "Lloyd", "Forgy",
       "MacQueen")
#hclustm<-c("ward.D", "ward.D2", "single", "complete","average","mcquitty","median","centroid")

#system(paste0("mkdir -p ","\"",str_to_title(paste("Hierarchial Clustering",hclustm[1],"Linkage using",distm[1],"algorithm")),"\""))
for( i in alg)
{   set.seed(500)
  system(paste0("mkdir -p ","\"",str_to_title(paste("K-Means using",i,"algorithm")),"\""))
  setwd(paste0("./",str_to_title(paste("K-Means using",i,"algorithm"))))
  clusters <-kmeans(synthetic_control,6,algorithm = i,iter.max = 20000 )
  ari<-ARI(as.factor(clusters$cluster),as.factor(real))
  vi<-variation_info(as.factor(clusters$cluster),as.factor(real))
  m<-t(as.matrix(c(round(ari,3),round(vi,3))))
  colnames(m)<-c("ARI","VI")
  sink(str_to_title(paste("K-Means using",i,"algorithm",".txt")))
  prmatrix(m,rowlab = rep_len("", ncol(m)))
  sink()
  df1<-mutate(synthetic_control,clusters$cluster)
  ggplot(df1,aes(x=clusters$cluster))+geom_bar()+labs(x="Predicted Cluster",title=str_to_title(paste("K-Means using",i,"algorithm")))
  ggsave( paste0 ( str_to_title(paste("K-Means using",i,"algorithm")),".png") , width =9,height=5.064,dpi=700 )
  setwd("..")
}
setwd("/home/scyther/Documents/clustergi/")
