setwd("/home/scyther/Documents/clustergi/kmedoids")
distm<-c("euclidean","manhattan","chebyshev","canberra","braycurtis","pearson_correlation","mahalanobis","cosine")
#hclustm<-c("ward.D", "ward.D2", "single", "complete","average","mcquitty","median","centroid")
library(ClusterR)
library(aricode)
library(cluster)
library(clevr)
library(dplyr)
#system(paste0("mkdir -p ","\"",str_to_title(paste("Hierarchial Clustering",hclustm[1],"Linkage using",distm[1],"distance")),"\""))
for( i in distm)
{   set.seed(500)
  system(paste0("mkdir -p ","\"",str_to_title(paste("Partitioning around Medoids using",i,"distance")),"\""))
    setwd(paste0("./",str_to_title(paste("Partitioning around Medoids using",i,"distance"))))
    clusters <- Cluster_Medoids(synthetic_control,clusters=6,distance_metric = i,threads = 4,swap_phase = TRUE,seed = 500)
    ari<-ARI(as.factor(clusters$clusters),as.factor(real))
    vi<-variation_info(as.factor(clusters$clusters),as.factor(real))
    m<-t(as.matrix(c(round(ari,3),round(vi,3))))
    colnames(m)<-c("ARI","VI")
    sink(str_to_title(paste("Partitioning around Medoids using",i,"distance",".txt")))
    prmatrix(m,rowlab = rep_len("", ncol(m)))
    sink()
    df1<-mutate(synthetic_control,clusters$clusters)
    ggplot(df1,aes(x=clusters$clusters))+geom_bar()+labs(x="Predicted Cluster",title=str_to_title(paste("Partitioning around Medoids using",i,"distance")))
    ggsave( paste0 ( str_to_title(paste("Partitioning around Medoids using",i,"distance")),".png") , width =9,height=5.064,dpi=700 )
    setwd("..")
  }
